name: CI
on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Build
        uses: goreleaser/goreleaser-action@v5
        if: github.ref_type != 'tag'
        with:
          args: release --snapshot --skip publish

      - name: Release
        uses: goreleaser/goreleaser-action@v5
        if: github.ref_type == 'tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release --clean

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: hookstream
          path: dist/*

